
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

/**
 * `env("DATABASE_URL")` throws during Vercel `npm install` / postinstall because
 * vars are often unavailable there. `prisma generate` does not connect; a
 * placeholder is enough until migrate/runtime when DATABASE_URL is set.
 */
const databaseUrl =
  process.env.DATABASE_URL ?? "file:./prisma/dev.db";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  engine: "classic",
  datasource: {
    url: databaseUrl,
  },
});
